repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
            exclude: frontend/libs/apiclient/
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black", "--filter-files"]

    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black
            args: [--line-length, "120", "."]
            language_version: python3.11

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.0
      hooks:
          - id: ruff
            args: [--fix]
